language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - CI=false yarn build
deploy:
  cleanup: false
  provider: firebase
  token:
    secure: "ejURQigwZpf98euV0VFCBlmn7+kdRH4lyYTr3k5+v2eCER399Ee9jwe610VcaNJbt+YiINfivNLEn/VodV5yFWLxVCqdiH73NbjuaiRh4G7fDL/Ph0sOrV8G/3Q01xO96zv6cgv5G4S6KU/mqLhzX7CS5kSSzbVMn1dE6H0uAwsVoX9q/mAUr05cM+PCCFOPu/hHI1D3aZv6466JvuHHTznaPSO0I/rTmxf+OrxEHO/ixArSoMC+8RWmaRKXKiqoi3KpUWU4z5Zn1kft4Gr5AGKaIHaIAjemt86WX15lLxzIMzNvXt/YdsrNsv9jmaQ+TBgSHh+MloXGHT+VgVOAraskifx5hiO/nBh7EUdhEFA/GWF1rl60u6drVm/F/UEgnm3WnsikEWcibAuez3thBwWyVSHyGLtAHj/Zr+LkiT11XiivAsM6Ppn78qfx+CdUgTEViv6hcxDSe5UDZO6DCN30/G1RHS2BwTE2XyAOLujT4me9jqamgXv3tiTZewfPPWooDzUKqpomqe7XIfrX+/NHEZQtH18bCtNJViuQ6Dc/p5oNXER/TV0wDkKz6PxXGsq+S3VVsjt22oIstIlNYCwgAWhcOQ+I/XV+Y1BXYvJc9K0D1x1XtJmiMguRk0dTX4n+Tx3fDnqUZwzRaaOeIjtNGqmY/ncDXiE2lpk59e0="
