language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - CI=false yarn build
on:
  branch: master
deploy:
  provider: firebase
  token:
    secure: "pyKkOgFsb67IpneQoeW6MAwH+Dj99iGRf67GhdgdNc+GBBavQVc2keqi+OoQSP6YmV5KJyQdlKOZn6ZdPDzZDQs2QQiHr+5kFqSpaGSvW01EqNxxWUHGw5t42/Umz16zndXe0BnvJrQqONxwKCZj1s4so77/LpLFxNA8lkrH1V/+YwzGgJ/LuqTYxyiW+B1RMXUhIIdV5ohnUFKWbGvDR2dJSHmoheathcjgGHQRDA/wyVvCvGqQs01RcPSCldPe0In4K12t3iDmVZyHZhTskPmLP5car7HVP8FW7YWB9zXWaSpK8VjPg0sVpsllUuUE64O22G71NnJb3fLEEupgWtgNL2g/Umj0nGWWp7mRKxq7w6NvMDy1OvRweaqxZVVnQFHJtzbyeNJK75wpRjDiROSibd7rLANRkl5b7T9PGgSft+F2L0sOzxIHCQrj+blHhtM20ONytmCZqx8aOkiveVi42SXGS2YkOkIuRgzJ1RfQtwLG3ArvBKrmHtSGBqNXyf9ytUPtfCS/hehymoLOIancvujfYTNxPIsvoC7duRMdcZkm+nQt2/5Xvz2ZeXdOADZh3jWyrVVBXJq96E1cV7fcQy4BihLTV5iU+GDj0x2ZEoWEY9fGBAZyX3YmRxi3VOJDklFGhL1Iem9hyKYdOKT94L3QQAk8TxmOOjdcmmk="
